# Generated by Django 2.2.7 on 2019-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceName', models.CharField(max_length=250)),
                ('accessLevel', models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Append'), (3, 'Write'), (4, 'Delete')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Role_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5, unique=True)),
                ('accessLevel', models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Append'), (3, 'Write'), (4, 'Delete')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=5, unique=True)),
                ('mail_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
