# Generated by Django 2.2.7 on 2019-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('keywordsAudit', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='wareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2500)),
                ('addDate', models.DateField(auto_now_add=True)),
                ('assigne', models.CharField(default='01/01/1996', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
