# Generated by Django 2.2.7 on 2019-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0002_auto_20191221_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='claims',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
