# Generated by Django 2.2.7 on 2019-12-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0003_auto_20191221_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionaudit',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
