# Generated by Django 2.2.7 on 2019-12-22 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0005_auto_20191222_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='addDate',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
