# Generated by Django 2.2.7 on 2019-12-22 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0007_auto_20191222_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role_id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='addDate',
            field=models.DateField(blank=True),
        ),
    ]
