# Generated by Django 2.2.7 on 2019-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_app', '0008_auto_20191222_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='addDate',
            field=models.DateField(auto_now=True),
        ),
    ]
